name: magician_ai
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  mix_annotations:
    path: packages/mix/packages/mix_annotations
  mix_generator:
    path: packages/mix/packages/mix_generator
  mix:
    path: packages/mix/packages/mix
  remix:
    path: packages/mix/packages/remix
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.3
  langchain: ^0.7.4
  langchain_community: ^0.3.0
  langchain_ollama: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/